# --- Configura\u00e7\u00e3o do Banco de Dados ---

# 1. A URL: O nome do banco tem que ser ID\u00caNTICO ao do Passo 2
spring.datasource.url=jdbc:mariadb://localhost:3306/scaf_tcc_db

# 2. O Usu\u00e1rio: O usu\u00e1rio que ela usa para logar no HeidiSQL (Passo 1)
spring.datasource.username=root

# 3. A Senha: A senha EXATA que ela usa no HeidiSQL (Passo 1)
# (Se ela n\u00e3o usa senha, deixe esta linha em branco, assim: spring.datasource.password=)
spring.datasource.password=2025ppjazp

# --- Configura\u00e7\u00e3o do JPA (Deixe como est\u00e1) ---
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true