spring.datasource.url=jdbc:mariadb://localhost:3306/nome_do_banco

# Coloque o usu\u00e1rio e senha do seu MariaDB (o padr\u00e3o do XAMPP/WAMP \u00e9 'root' e senha em branco)
spring.datasource.username=root
spring.datasource.password=sua_senha_se_tiver

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# --- Configura\u00e7\u00f5es do JPA (O "tradutor") ---
# 'update': O Spring vai ler suas classes Java (@Entity) e vai 
# comparar com o banco. Se a tabela n\u00e3o existir, ele cria. 
# Se uma coluna nova existir na classe, ele adiciona no banco.
# Perfeito para desenvolvimento!
spring.jpa.hibernate.ddl-auto=update

# Mostra no console os comandos SQL que o Spring est\u00e1 executando por baixo dos panos
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true