insert into fabricante (name) value ('AAB');
insert into fabricante (name) value ('AIRMARINE');
insert into fabricante (name) value ('ALFA LAVAL');
insert into fabricante (name) value ('Alfalaval');
insert into fabricante (name) value ('BUSCH');
insert into fabricante (name) value ('EBARA');
insert into fabricante (name) value ('FLOWSERVE');
insert into fabricante (name) value ('GARO');
insert into fabricante (name) value ('HBR');
insert into fabricante (name) value ('Hilliard');
insert into fabricante (name) value ('HSV');
insert into fabricante (name) value ('Ingersoll-Rand');
insert into fabricante (name) value ('KSB');
insert into fabricante (name) value ('LEWA');
insert into fabricante (name) value ('MCFARLAND-TRITAN, LCC');
insert into fabricante (name) value ('NETZCH');
insert into fabricante (name) value ('Peroni');
insert into fabricante (name) value ('Rolls Royce');
insert into fabricante (name) value ('Rotork');
insert into fabricante (name) value ('SULZER');
insert into fabricante (name) value ('Tormene');
insert into fabricante (name) value ('Wartsila');
insert into fabricante (name) value ('WEG');
insert into fabricante (name) value ('WEIR VALVES');




-- insert into instalacao (name) value ('UN-BS/ATP-IMI/OP-P68');
-- insert into instalacao (name) value ('UN-BS/ATP-IMI/OP-P70');
-- insert into instalacao (name) value ('UN-BS/ATP-IMI/OP-P71');
-- insert into instalacao (name) value ('UN-BS/ATP-IMI/OP-PMXL');


insert into sistema (name) value ('FAIN-Sist de Água Industrial');
insert into sistema (name) value ('FAPO-Sist de Água Potável');
insert into sistema (name) value ('FCOE-Sist de Estruturas, Convés e Casco');
insert into sistema (name) value ('FECC-Sist de Corrente Contínua ou UPS');
insert into sistema (name) value ('FECR-Sist de Retificação de Potência (SCR)');
insert into sistema (name) value ('FEDE-Sist de Distribuição Essencial');
insert into sistema (name) value ('FEDN-Sist de Distribuição Normal');
insert into sistema (name) value ('FEEM-Sist de Distribuição de Emergência');
insert into sistema (name) value ('FEEP-Sist de Distribuição Principal');
insert into sistema (name) value ('FEIE-Sist de Iluminação de Emergência');
insert into sistema (name) value ('FEIN-Sist de Iluminação Normal');
insert into sistema (name) value ('FEIS-Sist de Iluminação Essencial');
insert into sistema (name) value ('FEPC-Sist de Proteção Catódica');
insert into sistema (name) value ('FQAV-Sist de Abastecimento de Aeronaves (QAV)');
insert into sistema (name) value ('FSAC-Sist de Ar Comprim de Serv e Instrum');
insert into sistema (name) value ('FSAL-Sist de Acomodações, Oficinas e Outros');
insert into sistema (name) value ('FSAN-Sist de Ancoragem');
insert into sistema (name) value ('FSAP-Sist de Ar de Partida');
insert into sistema (name) value ('FSAQ-Sist de Água Quente de Processo');
insert into sistema (name) value ('FSAR-Sist de Condicionamento de Ar');
insert into sistema (name) value ('FSCA-Sist de Captação de Água Salgada');
insert into sistema (name) value ('FSCI-Sist de Combate a Incêndio');
insert into sistema (name) value ('FSFG-Sist de Detecção de Fogo e Gás');
insert into sistema (name) value ('FSGE-Sist de Geração de Emergência');
insert into sistema (name) value ('FSGA-Sist de Geração Auxiliar');
insert into sistema (name) value ('FSGP-Sist de Geração Principal');
insert into sistema (name) value ('FSGV-Sist de Geração de Vapor');
insert into sistema (name) value ('FSHI-Sist Hidráulico Centralizado');
insert into sistema (name) value ('FSIS-Sist de Inspeção Submarina');
insert into sistema (name) value ('FSLE-Sist de Lastreamento');
insert into sistema (name) value ('FSES-Sist de Esgotamento');
insert into sistema (name) value ('FSMC-Sist de Movimentação de Cargas');
insert into sistema (name) value ('FSOD-Sist de Óleo Diesel');
insert into sistema (name) value ('FSRA-Sist de Água de Resfriamento');
insert into sistema (name) value ('FSRF-Sist de Câmara Frigorífica');
insert into sistema (name) value ('FSSV-Sist de Salvatagem');
insert into sistema (name) value ('FSTD-Sist de Tratamento Dejetos Sanitários');
insert into sistema (name) value ('FSTI-Sist de Telecomunicação e Informática');
insert into sistema (name) value ('FSVE-Sist de Ventilação e Exaustão');
insert into sistema (name) value ('PSAI-Sist de Injeção de Água');
insert into sistema (name) value ('PSCC-Sist de Compressão de CO2');
insert into sistema (name) value ('PSCG-Sist de Compressão/Recompressão de Gás');
insert into sistema (name) value ('PSCO-Sist de Coleta de Superfície');
insert into sistema (name) value ('PSSE-Sist de Separação de Fluídos');
insert into sistema (name) value ('PSCP-Sist Controle Poços - Un. Hidráulica');
insert into sistema (name) value ('PSEG-Sist de Escoamento de Gás');
insert into sistema (name) value ('PSEP-Sist de Escoamento de Óleo');
insert into sistema (name) value ('PSFL-Sist de Flare');
insert into sistema (name) value ('PSGC-Sist de Gás Combustível');
insert into sistema (name) value ('PSGI-Sist de Gás Inerte');
insert into sistema (name) value ('PSGL-Sist de Distribuição de Gás Lift');
insert into sistema (name) value ('PSIG-Sist de Distribuição Gás para Injeção');
insert into sistema (name) value ('PSIQ-Sist de Injeção Química');
insert into sistema (name) value ('PSOF-Sist de Offloading');
insert into sistema (name) value ('PSSC-Sist de Automação Industrial');
insert into sistema (name) value ('PSTA-Sist de Tratamento de Água Produzida');
insert into sistema (name) value ('PSTG-Sist de Tratamento de Gás');
insert into sistema (name) value ('PSTP-Sist de Tratamento de Petróleo');
insert into sistema (name) value ('PSMF-Sist de Medição de Fluidos');
insert into sistema (name) value ('PSTR-Sist do Turret');
insert into sistema (name) value ('PSVA-Sist de Vent Atmosférico');
insert into sistema (name) value ('PDFC-Sist Drenag Fech Área Classif Recup Cond');
insert into sistema (name) value ('PDAC-Sist Drenagem Aberta Área Classificada');
insert into sistema (name) value ('PSEL-Sist de Elevação');
insert into sistema (name) value ('PURV-Unidade Recuperadora de Vapor');
insert into sistema (name) value ('SCPP-Sist de Ferramentas e Coluna Perfuração');
insert into sistema (name) value ('SDMT-Sist de Dados Meteorológicos');
insert into sistema (name) value ('SGRA-Sist de Granéis');
insert into sistema (name) value ('SPDN-Sist de Posicionamento');
insert into sistema (name) value ('SSEG-Segurança-Proteção Coletiva e Individual');
insert into sistema (name) value ('SSER-Sist de Elevação e Rotação');
insert into sistema (name) value ('SSLA-Sist de Lama');
insert into sistema (name) value ('SSMT-Sist de Manuseio de Tubos');
insert into sistema (name) value ('SSSP-Sist de Segurança de Poço');
insert into sistema (name) value ('SSTC-Sist de Tensionam. e Compens. Movimento');
insert into sistema (name) value ('PSPU-Sist de Pull in / Pull out');


insert into setor_atuacao (name) value ('Engenharia');
insert into setor_atuacao (name) value ('Inspeção de Equipamentos');
insert into setor_atuacao (name) value ('Manutenção');
insert into setor_atuacao (name) value ('Operação');
insert into setor_atuacao (name) value ('SMS');

insert into status (id, name) value (1, 'Em Análise');
insert into status (id, name) value (2, 'Aprovada');
insert into status (id, name) value (3, 'Recusada');

insert into tipo_usuario (id, name) value (1, 'Comum');
insert into tipo_usuario (id, name) value (2, 'Gerente');
insert into tipo_usuario (id, name) value (3, 'Administrador');
